from django.urls import path
from . import bib_photos_view, events_views, views, users_view, photos_view, bibs_view, face_photos_view, cloud_storage_view, api_views

urlpatterns = [
    path('', views.home_view, name='home'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('profile/', views.update_profile, name='update_profile'),
    path('password/', views.change_password, name='change_password'),
    path('users/', users_view.users, name='users'),
    path('users/data/', users_view.users_data, name='users_data'),
    path('users/add/', users_view.add_user, name='add_user'),
    path('users/<int:user_id>/edit/', users_view.edit_user, name='edit_user'),
    path('users/<int:user_id>/delete/', users_view.delete_user, name='delete_user'),
    path('users/<int:user_id>/change-password/', users_view.change_password, name='change_password'),
    path('events/', events_views.events, name='events'),
    path('event_list/', events_views.event_list, name='event_list'),
    path('events/data/', events_views.events_data, name='events_data'),
    path('events/add/', events_views.add_event, name='add_event'),
    path('events/<int:event_id>/view/', events_views.view_event, name='view_event'),
    path('events/<int:event_id>/edit/', events_views.edit_event, name='edit_event'),
    path('events/<int:event_id>/delete/', events_views.delete_event, name='delete_event'),
    path('photos/', photos_view.photos, name='photos'),
    path('photos/data', photos_view.photos_data, name='photos_data'),
    path('photos/<int:photo_id>/delete/', photos_view.delete_photo, name='delete_photo'),
    path('bibs/', bibs_view.bibs, name='bibs'),
    path('bibs/data/', bibs_view.bibs_data, name='bibs_data'),
    path('bibs/add/', bibs_view.create_or_edit_bib, name='add_bib'),
    path('bibs/<int:bib_id>/edit/', bibs_view.create_or_edit_bib, name='edit_bib'),
    path('bibs/<int:bib_id>/delete/', bibs_view.delete_bib, name='delete_bib'),
    path('bibs/import/', bibs_view.import_bib, name='import_bib'),
    path('bib_photos/', bib_photos_view.bib_photos, name='bib_photos'),
    path('bib_photos/data/', bib_photos_view.bib_photos_data, name='bib_photos_data'),
    path('bib_photos/<int:bib_photo_id>/delete/', bib_photos_view.delete_bib_photo, name='delete_bib_photo'),
    path('face_photos/', face_photos_view.face_photos, name='face_photos'),
    path('face_photos/data/', face_photos_view.face_photos_data, name='face_photos_data'),
    path('face_photos/<int:face_photo_id>/delete/', face_photos_view.delete_face_photo, name='delete_face_photo'),
    path('cloud_storage/', cloud_storage_view.cloud_storage, name='cloud_storage'),
    path('cloud_storage/data/', cloud_storage_view.cloud_storage_data, name='cloud_storage_data'),
    path('cloud_storage/add/', cloud_storage_view.create_or_edit_cloud_storage, name='add_cloud_storage'),
    path('cloud_storage/<int:cloud_storage_id>/edit/', cloud_storage_view.create_or_edit_cloud_storage, name='edit_cloud_storage'),
    path('cloud_storage/<int:cloud_storage_id>/delete/', cloud_storage_view.delete_cloud_storage, name='delete_cloud_storage'),
    path('api/events/', api_views.api_list_events, name='api_list_events'),
    path('api/event/<int:event_id>/', api_views.api_event_detail, name='api_event_detail'),
    path('api/cloud_storage/<int:cloud_storage_id>/', api_views.api_cloud_storage_detail, name='api_cloud_storage_detail'),
    path('api/cloud_storage/<int:cloud_storage_id>/photos/', api_views.api_list_photos, name='api_list_photos'),
    path('api/cloud_storage/<int:cloud_storage_id>/photos/add/', api_views.api_save_photos, name='api_save_photos'),
    path('api/cloud_storage/<int:cloud_storage_id>/photos/update/', api_views.api_update_photos, name='api_update_photos'),
    path('api/cloud_storage/<int:cloud_storage_id>/photos/delete/', api_views.api_delete_photos, name='api_delete_photos'),
    path('api/photo/<int:photo_id>/result/', api_views.api_add_photos_result, name='api_add_photos_result'),
    path('api/search/', api_views.search_photo, name='search_photo'),
]

